### ISSUE TITLE
"quantize" optimization

### ISSUE THREAD

**Issue by alexozer** [aldelaro5/ghidra-gekko-broadway-lang#1]
The README states:

> consider setting the GQR values so it can properly assume their contents as most games will set them without changing them after

I'm not exactly sure how to go about doing this? Some brief guidance for how to do this in Ghidra would be much appreciated.

**Comment by aldelaro5** [comment]
Sorry for the delay.

You have to go in a menu called "register manager" accessible from the Window menu which allows you to tell ghidra to assume the value of the register over a range of address. You would just have a range that represents....everything like most likely, it would be from 0x00000000 to 0x94000000. Once you knwo the values of the GQR (use the dolphin debugger to get them), that's where you set them.

**Comment by alexozer** [comment]
Thank you!
